database: &database
  database: spotcode_master

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

user: &user
  username: nicolas
  password: 123456

development:
  <<: *default
  <<: *user
  <<: *database
